### ISSUE TITLE
Feature request: Ability to ignore certain folder in the search path

### ISSUE THREAD

**Issue by nikhilgeo** [securing/DumpsterDiver#18]
If there is an option to ignore certain paths with in the search path it will very useful. 
For example a test folder with in search path if required to be ignored. So if there is an switch to ignore paths with certain text it will be great.

meanwhile i'm enjoying using ur tools.

**Comment by xep624** [comment]
Hi @nikhilgeo !

Thanks for your comment. So far there's no such option and all subfolders are included, BUT it would be really useful feature. Actually, I'm working on better anti-false positive rules, but now I see that in some cases it's possible to limit fp just by not scanning certain files :) So really appreciate your request :) Soon I will add this feature.

Actually, I see here 2 features:
1) Specify a file with a list and you can choose to either scan only file paths from the file or scan everything except file paths specified in this file

2) Define search strings - if the file contains any of specified string only this file will be scanned or any file except those containing the strings.

Would you add anything to it?

**Comment by nikhilgeo** [comment]
Hi @xep624,

I would suggest a modified second approach:

Have a switch which can be used to specify a regular expression, and if that regular expression is in file path or file name skip it.

For example:
`DumpsterDiver.py -newFlag *test*`

This will skip something like below:
```
TestFile.java
/test/login.java
etc
```

**Comment by xep624** [comment]
Hi @nikhilgeo !

I've just added requested features. There's a new flag to specify unwanted files via bad expressions (just add flag --bad expressions "I don't want to see file which contain this string") or via file names/extensions (--exclude-files test1.txt test.txt). Description of new features can be found here: 
https://github.com/securing/DumpsterDiver#limiting-scan

I'm closing this issue now, however if you want to add something to it please feel free to reopen. Thanks!
