### ISSUE TITLE
Question: files type supported? 

### ISSUE THREAD

**Issue by francesco1119** [securing/DumpsterDiver#3]
Hello, 
Do you have a list of files that can be read by your tool? 
docs? PDF?

**Comment by xep624** [comment]
Hi! There's no such list yet. Basically it can analyze any text file (e.g. .config, .sql, .php, .json, .xls, .csv, etc.). Additionally it can decode git objects (git logs are kept in VAX COFF format) and can uncompress files from .zip, .tar.gz, .tgz, .tar.bz2, .tbz.
Regarding formats like .doc or .pdf I don't think they can be a good source of key leaks. However, if you think opposite I can add some more handlers :) 
Let me know what filetypes would be worth adding here so I'll try add the to the program.

**Comment by francesco1119** [comment]
I did something like your DumpsterDiver, is called [Pukekeo](https://github.com/francesco1119/Pukeko). Is written very badly :( 
By the way, I think most of the time passwords can be inside PFD, docx, e-mails and pictures. 
Pukeko creates a dictionary for bruteforce, so is a bit different from your DumpsterDiver.
You can read and open different files with [textract ](https://github.com/deanmalmgren/textract) but is a bit hard to install. 
When you have huge amount of GB leaked from a corporation you don't only have e-mails, you have everything.

**Comment by xep624** [comment]
So it's like CeWL (https://github.com/digininja/CeWL) but for offline input files? Pretty nice idea. Thing I don't understand is how are you going to find passwords in picture or .mp3 files?
Thanks for suggesting textract - I have to check it out.
Regarding passwords, the DumpsterDiver is supposed to find secret keys base on high entropy, what is not an effective attitude in finding a password. However, you've just inspired me to add such module to look for strong passwords - thanks a lot!

**Comment by xep624** [comment]
Regarding textract I found the list of [filetypes it supports ](http://textract.readthedocs.io/en/stable/) and actually DumpsterDiver is just missing .doc, .docx and .pdf. Taking into account problems with installing textract I think it will be better to add separate handlers for docs and pdfs.

**Comment by francesco1119** [comment]
Indeed, Textract can be a pain in the a**. 
Thanks for the CeWL link. 

- Passwords in .mp3 files > 0,000000000001 chance to find one. And is a pain in the a** because it needs to listen to the whole .mp3. But don't forget that in a corporate environment many times VoIP technologies are connected with Outlook or any other mail client and you end up receiving recorded voice messages in your inbox. Many times people uses 2 factor authentications: this leads to passwords sent through phone calls or recoded voice messages. I agree, is not so common and most of the time that password changes... however I wanted to keep this feature.
- Passwords in images > well, how many times you don't have paper and pen and you take a picture of a wifi password or a TeamViewer ID/Password? ;) Look into your phone or into your Picture/Documents folders...

This was a very productive chat, thank you
